spring.application.name=springio
jobrunr.background-job-server.enabled=true
jobrunr.dashboard.enabled=true
#spring.datasource.url=jdbc:postgresql://5.tcp.eu.ngrok.io:10873/postgres
#spring.datasource.username=postgres
#spring.datasource.password=postgres
#spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.ai.ollama.chat.model=gemma4:26b